### ISSUE TITLE
Multiple devices on single IP causes errors

### ISSUE THREAD

**Issue by splatch** [Code-House/bacnet4j-wrapper#6]
Reported on openhab forums:
```
Exception in thread “bacnet-client-2-discovery” java.lang.IllegalArgumentException: Not an I/P mac
at com.serotonin.bacnet4j.npdu.ip.IpNetworkUtils.getIpBytes(IpNetworkUtils.java:115)
at com.serotonin.bacnet4j.npdu.ip.IpNetworkUtils.toIpString(IpNetworkUtils.java:106)
at com.serotonin.bacnet4j.npdu.ip.IpNetworkUtils.toIpPortString(IpNetworkUtils.java:110)
at com.serotonin.bacnet4j.npdu.ip.IpNetworkUtils.toString(IpNetworkUtils.java:122)
at org.code_house.bacnet4j.wrapper.api.Device.toString(Device.java:114)
at java.lang.String.valueOf(String.java:2994)
at java.lang.StringBuilder.append(StringBuilder.java:131)
at org.openhab.binding.bacnet.internal.BacNetBinding.deviceDiscovered(BacNetBinding.java:250)
at org.code_house.bacnet4j.wrapper.api.DiscoveryCallable.iAmReceived(DiscoveryCallable.java:89)
at org.code_house.bacnet4j.wrapper.api.util.ForwardingAdapter$2.run(ForwardingAdapter.java:77)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

https://community.openhab.org/t/bacnet-binding-error-on-start/38822

**Comment by splatch** [comment]
This issue was resolved, additional safety measure was introduced in 623654f478e07ef195f19124759b2f3d803426c3.
